#include "collab/Sampler.h"

#include <algorithm>
#include <cmath>
#include <iomanip>
#include <sstream>

#include "collab/BuiltinInstruments.h"

namespace collab
{

namespace
{
    std::string fmt (double v)
    {
        std::ostringstream s;
        s.imbue (std::locale::classic());
        s << std::setprecision (4) << v;
        return s.str();
    }
}

bool isSampler (const Instrument& i)
{
    return i.kind == Instrument::Kind::builtin && i.id == builtin::sampler;
}

std::vector<SamplerPad> samplerPads (const nlohmann::json& params)
{
    std::vector<SamplerPad> pads ((size_t) kSamplerPads);

    for (int i = 0; i < kSamplerPads; ++i)
        pads[(size_t) i].note = 36 + i;

    if (! params.is_object() || ! params.contains ("pads") || ! params["pads"].is_array())
        return pads;

    const auto& list = params["pads"];

    for (size_t i = 0; i < list.size() && i < pads.size(); ++i)
    {
        const auto& j = list[i];

        if (! j.is_object())
            continue;

        auto& p = pads[i];
        p.note = std::clamp (j.value ("note", p.note), 0, 127);
        p.audioHash = j.value ("audioHash", std::string());
        p.name = j.value ("name", std::string());
        p.gainDb = std::clamp (j.value ("gainDb", 0.0), -60.0, 24.0);
        p.pan = std::clamp (j.value ("pan", 0.0), -1.0, 1.0);
        p.tuneSemitones = std::clamp (j.value ("tune", 0.0), -24.0, 24.0);
        p.oneShot = j.value ("oneShot", true);
        p.chokeGroup = std::clamp (j.value ("choke", 0), 0, 16);
        p.sourceBpm = j.value ("bpm", 0.0);
        p.sourceBpm = p.sourceBpm > 0.0 ? std::clamp (p.sourceBpm, 20.0, 400.0) : 0.0;
    }

    return pads;
}

nlohmann::json withSamplerPads (const nlohmann::json& params, const std::vector<SamplerPad>& pads)
{
    nlohmann::json result = params.is_object() ? params : nlohmann::json::object();
    nlohmann::json list = nlohmann::json::array();

    for (auto& p : pads)
    {
        nlohmann::json j { { "note", p.note } };

        if (! p.audioHash.empty())  j["audioHash"] = p.audioHash;
        if (! p.name.empty())       j["name"] = p.name;
        if (p.gainDb != 0.0)        j["gainDb"] = p.gainDb;
        if (p.pan != 0.0)           j["pan"] = p.pan;
        if (p.tuneSemitones != 0.0) j["tune"] = p.tuneSemitones;
        if (! p.oneShot)            j["oneShot"] = false;
        if (p.chokeGroup != 0)      j["choke"] = p.chokeGroup;
        if (p.sourceBpm > 0.0)      j["bpm"] = p.sourceBpm;

        list.push_back (j);
    }

    result["pads"] = list;
    return result;
}

std::string generateSamplerSfz (const nlohmann::json& params, const std::function<std::string (const SamplerPad&)>& samplePath)
{
    std::ostringstream s;
    s.imbue (std::locale::classic());
    s << "// generated by ShareDAW for builtin.sampler\n<control> default_path=\n";

    int index = 0;

    for (auto& p : samplerPads (params))
    {
        ++index;

        if (p.audioHash.empty())
            continue;

        auto path = samplePath ? samplePath (p) : std::string();

        if (path.empty())
            continue;

        std::replace (path.begin(), path.end(), '\\', '/');

        s << "<region> sample=" << path << " key=" << p.note << " pitch_keycenter=" << p.note
          << " amp_veltrack=100 ampeg_attack=0.001 ampeg_release=" << (p.oneShot ? "0.05" : "0.12");

        if (p.oneShot)
            s << " loop_mode=one_shot";

        if (p.gainDb != 0.0)
            s << " volume=" << fmt (p.gainDb);

        if (p.pan != 0.0)
            s << " pan=" << fmt (p.pan * 100.0);

        if (p.tuneSemitones != 0.0)
        {
            const double cents = std::round (p.tuneSemitones * 100.0);
            s << " transpose=" << (int) (cents / 100.0) << " tune=" << (int) std::fmod (cents, 100.0);
        }

        // チョーク: 同じグループの音は後の音が前を止める。グループがなければ同じパッドの重なりだけ止めない
        if (p.chokeGroup > 0)
            s << " group=" << (100 + p.chokeGroup) << " off_by=" << (100 + p.chokeGroup) << " off_mode=fast";

        s << "\n";
    }

    return s.str();
}

std::vector<std::string> referencedAudio (const Project& p)
{
    std::vector<std::string> hashes;

    auto add = [&] (const std::string& h)
    {
        if (! h.empty() && std::find (hashes.begin(), hashes.end(), h) == hashes.end())
            hashes.push_back (h);
    };

    for (auto& t : p.tracks)
    {
        if (t.render)
            add (t.render->audioHash);

        for (auto& c : t.audioClips)
            add (c.audioHash);

        if (t.instrument && isSampler (*t.instrument))
            for (auto& pad : samplerPads (t.instrument->params))
                add (pad.audioHash);
    }

    return hashes;
}

}
